apiVersion: v1
kind: Service
metadata:
  name: service-bg
  labels:
    app: service-bg
spec:
  type: LoadBalancer
  selector:
    app: service-blue   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080